spring.application.name=notificationService

# Kafka consumer group và c?ng server Kafka
spring.kafka.consumer.group-id=notificationGroup
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094
#kafka server url
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.mail.host = smtp.gmail.com
spring.mail.port=587
spring.mail.username=tpvinh292931@gmail.com
spring.mail.password=urcejfpvdjnzlvxs
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
